### ISSUE TITLE
timeout needed between "prepare" and "do query" on some cards

### ISSUE THREAD

**Issue by compholio** [Ognian/sdmon#6]
we used this successfully with a Kingston card and found that we needed a delay for reliable behavior (100 ms didn't work, 1 second did):
```
diff --git a/src/sdmon.c b/src/sdmon.c
index b4c35ad..b6a0929 100644
--- a/src/sdmon.c
+++ b/src/sdmon.c
@@ -221,6 +221,7 @@ int main(int argc, const char *argv[]) {
     // printf("\"error\":\"1st CMD56 CALL FAILED: %s\"\n}\n", strerror(errno));
     // exit(1);
   }
+  usleep(1000000);
 
   // do query smart data
   cmd56_arg = 0x00000021;
```

**Comment by Ognian** [comment]
Thanks a lot for reporting this @compholio.
Could you provide more information about the Kingston card (model, type etc..) since I haven't tested with it, and could you provide the output of a successful run of sdmon?
So it looks like the Kingston card behaves like Apacer. At the beginning I also noticed that adding a wait here helps, but the reason why it helped was actually due to problems in the linux driver. What happened was that the driver hangs up after sending the first cmd56, the os detects this and resets the driver after aprox. 1 second, so that the second cmd succeeds...
The real problem with this is that the sd io is blocked for about 1 second, in case this is your only disk (like i.e. raspberry pi) this could be fatal for other processes...
Anyway I'll add an additional optional sdmon switch to add a timeout, so that this case is also covered.

**Comment by Ognian** [comment]
As far as I know the `avgEraseCount` is what the card keeps track of. Based on this and the max value for this kind of cards the card is calculating `enduranceRemainLifePercent`. If `avgEraseCount`gets above the max value the `enduranceRemainLifePercent`could be totally wrong... For the very first Apacer card I tested (2017, 2018) I was told that such a max value is about 3k (3000). Looking at your results everything looks reasonable ...

I have implemented the -a option in the latest development build.

I was testing on a raspberry pi where the sd card is also the system disk, and therefore noticed such kernel driver problems, I was also very lucky since one of the raspberry pi sd card driver developers contacted me and was able to reproduce and fix the problem, so no idea if on a laptop this even could be a problem...

**Comment by Ognian** [comment]
Fortunately the issue was documented on github, so here it is: https://github.com/raspberrypi/linux/issues/2728 .

**Comment by compholio** [comment]
Nope, none of the controllers we're using are the bcm2835.

With a little searching I found a public document describing this feature ( https://webshop.cedel.nl/Files/8/120000/120581/Attachments/Product/5864y43udmvs8104709000j5OPLg830O.pdf ) and it shows that the first command has no expected data packet or response:
![image](https://user-images.githubusercontent.com/1738066/179249560-f2265c48-3c18-43aa-8fc5-6c8ae69d5e02.png)

Unfortunately, my attempts at modifying the code to match this behavior don't seem to fix the problem.  I would suspect that the flash controller in these Kingston card's is just a little finicky and need an extra delay to behave properly.

**Comment by Ognian** [comment]
Yes the above document is the one I had got from Apacer when started sdmon ...
Lets keep it this way.
Thanks again for your help.
